image: jangrewe/gitlab-ci-android

stages:
  - lint
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

lint:
  stage: lint
  script:
    - ./gradlew lint --warning-mode all

build:
  stage: build
  script:
    - ./gradlew assembleDebug